version: "3.8"
services:
  my:
    build: .
    container_name: web-server
    ports:
      - 8080:8080 # Management UI
    networks:
      - my-network
networks:
  my-network:
    name: my-network
    driver: bridge